Parameters:
  VpcCidrBlock:
    Type: String
    Description: CIDR block for the VPC

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Vpc-Name
          Value: databricks-vpc

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref VpcCidrBlock
      AvailabilityZone: ap-south-1

Outputs:
  VpcId:
    Value: !Ref MyVPC
